### PR TITLE
engine: make getHEAD match also HEAD, rewrite remote refs

### LINKED ISSUE #255: getHEAD method is filtering by refs/heads/HEAD instead of HEAD in bare or standard repositories formats.
This might or might not be connected to #254 but on similar use case of using Engine on a local Git repository and trying to count number of commits, one gets unexpected result.

Steps to reproduces:
```
mkdir test-repo-root
cd test-repo-root; git clone git@github.com:bblfsh/client-scala.git; cd -

"${SPARK_HOME}"/bin/spark-shell --packages "tech.sourced:engine:0.1.12"
```

And then

```
import tech.sourced.engine._
val engine = Engine(spark, "./test-repo-root/")
engine.getRepositories.getHEAD.getCommits.getFirstReferenceCommit.count
```
results in `0`.

Expected results would be closer to
```
$ cd
$ git rev-list HEAD --count
125
```

### PR DESCRIPTION
**Pull request by erizocosmico**
Fixes #255

### CODE REVIEW

File: src/main/scala/tech/sourced/engine/package.scala [hunk 1]
```diff
@@ -205,6 +205,9 @@ package object engine {
       }
     }
 
+    private val headRef = "refs/heads/HEAD"
```
Comment (mcarmonaa) [inline src/main/scala/tech/sourced/engine/package.scala]: Should the name's first letter be capitalized as the other constants?

File: src/main/scala/tech/sourced/engine/package.scala [hunk 2]
```diff
@@ -205,6 +205,9 @@ package object engine {
...
+    private val localHeadRef = "HEAD"
```
Comment (mcarmonaa) [inline src/main/scala/tech/sourced/engine/package.scala]: Same constant name style here

File: README.md [hunk 3]
```diff
@@ -209,6 +209,13 @@ scala> engine.getRepositories.filter('id === "github.com/mawag/faq-xiyoulinux").
 
 ```
 
+### Processing local repositories with the engine
+
+There are some design decisions that may surprise the user when processing local repositories, instead of siva files. This is the list of things you should take into account when doing so:
+
+- All local branches will belong to a repository whose id is `file://$REPOSITORY_PATH`. So, if you clone `https://github.com/foo/bar.git` at `/home/foo/bar`, you will see two repositories `file:///home/foo/bar` and `github.com/foo/bar`, even if you only have one.
+- Remote branches are transformed from `refs/remote/$REMOTE_NAME/$BRANCH_NAME` to `refs/heads/$BRANCH_NAME` as they will only belong to the repository id of their corresponding remote. So `refs/remote/origin/HEAD` becomes `refs/heads/HEAD`.
```
Comment (mcarmonaa) [inline README.md]: Aren't there name collision issues with that?

Comment (erizocosmico) [reply README.md]: Nope, they belong to different repositories. If you have a local branch that's `refs/heads/develop` and a `refs/remote/foo/develop` the second one will belong to `github.com/foo/bar` and the first one to `file:///yada/yada`

**Comment by erizocosmico** [comment]
@ajnavarro @jfontan @mcarmonaa perhaps we should add `is_remote` field to the `references` table? Since we're rewriting them, it could be useful to be able to filter by whether a ref is remote or not.

That way, local branches would be `false`, remote branches would be `true` and all siva branches would be `true` (because they all come from a remote, right?)

**Comment by jfontan** [comment]
I don't see any reason why we shouldn't add that field. It should make some reference filters faster.

**Comment by erizocosmico** [comment]
I will address that in another PR and merge this.
