### PR TITLE
iterator: skip RevWalkExceptions in RefWithCommitIterator

### LINKED ISSUE #336: RevWalkException in RefWithCommitIterator
## Expected Behavior

Engine should be able to analyze PGA.

## Current Behavior

It fails with exception:
```
Exception in thread "main" org.apache.spark.SparkException: Job aborted due to stage failure: Task 92 in stage 1.0 failed 4 times, most recent failure: Lost task 92.3 in stage 1.0 (TID 530, 10.2.101.146, executor 7): org.eclipse.jgit.errors.RevWalkException: Walk failure.
	at org.eclipse.jgit.revwalk.RevWalk.iterator(RevWalk.java:1331)
	at scala.collection.convert.Wrappers$JIterableWrapper.iterator(Wrappers.scala:54)
	at scala.collection.IterableLike$class.toIterator(IterableLike.scala:104)
	at scala.collection.AbstractIterable.toIterator(Iterable.scala:54)
	at tech.sourced.engine.iterator.RefWithCommitIterator.liftedTree1$1(CommitIterator.scala:141)
	at tech.sourced.engine.iterator.RefWithCommitIterator.hasNext(CommitIterator.scala:138)
	at tech.sourced.engine.iterator.ChainableIterator.hasNext(ChainableIterator.scala:89)
	at scala.collection.Iterator$class.isEmpty(Iterator.scala:330)
	at tech.sourced.engine.iterator.ChainableIterator.isEmpty(ChainableIterator.scala:16)
	at tech.sourced.engine.iterator.ChainableIterator.hasNext(ChainableIterator.scala:90)
	at scala.collection.Iterator$class.isEmpty(Iterator.scala:330)
	at tech.sourced.engine.iterator.ChainableIterator.isEmpty(ChainableIterator.scala:16)
	at tech.sourced.engine.iterator.ChainableIterator.hasNext(ChainableIterator.scala:90)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at tech.sourced.engine.iterator.CleanupIterator.hasNext(CleanupIterator.scala:23)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:438)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:395)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at com.datastax.spark.connector.util.CountingIterator.hasNext(CountingIterator.scala:12)
	at com.datastax.spark.connector.writer.GroupingBatchBuilder.next(GroupingBatchBuilder.scala:105)
	at com.datastax.spark.connector.writer.GroupingBatchBuilder.next(GroupingBatchBuilder.scala:31)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at com.datastax.spark.connector.writer.GroupingBatchBuilder.foreach(GroupingBatchBuilder.scala:31)
	at com.datastax.spark.connector.writer.TableWriter$$anonfun$writeInternal$1.apply(TableWriter.scala:233)
	at com.datastax.spark.connector.writer.TableWriter$$anonfun$writeInternal$1.apply(TableWriter.scala:210)
	at com.datastax.spark.connector.cql.CassandraConnector$$anonfun$withSessionDo$1.apply(CassandraConnector.scala:112)
	at com.datastax.spark.connector.cql.CassandraConnector$$anonfun$withSessionDo$1.apply(CassandraConnector.scala:111)
	at com.datastax.spark.connector.cql.CassandraConnector.closeResourceAfterUse(CassandraConnector.scala:145)
	at com.datastax.spark.connector.cql.CassandraConnector.withSessionDo(CassandraConnector.scala:111)
	at com.datastax.spark.connector.writer.TableWriter.writeInternal(TableWriter.scala:210)
	at com.datastax.spark.connector.writer.TableWriter.insert(TableWriter.scala:197)
	at com.datastax.spark.connector.writer.TableWriter.write(TableWriter.scala:183)
	at com.datastax.spark.connector.RDDFunctions$$anonfun$saveToCassandra$1.apply(RDDFunctions.scala:36)
	at com.datastax.spark.connector.RDDFunctions$$anonfun$saveToCassandra$1.apply(RDDFunctions.scala:36)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:108)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Log from worker: 
[stderr_worker.txt](https://github.com/src-d/engine/files/1767048/stderr_worker.txt)

## Steps to Reproduce (for bugs)

```
spark-shell --packages "tech.sourced:engine:0.5.2" --master="spark://p-spark-master:7077"

scala> import tech.sourced.engine._
import tech.sourced.engine._

scala> val engine = Engine(spark, "hdfs://hdfs-namenode/apps/borges/10k", "siva")
engine: tech.sourced.engine.Engine = tech.sourced.engine.Engine@4086e003

scala> engine.getRepositories.getHEAD.getCommits.getTreeEntries.count()
<fail>
```

## Context
running gemini

## Your Environment (for bugs)

* Version used: 0.5.2
* Src-d staging cluster

### PR DESCRIPTION
**Pull request by erizocosmico**
Fixes #336 

This is the cleanest way I found to solve this bug. What it does, basically, is preloading the next result in the `hasNext`. That way, if there's a problem doing so, we just skip it and call `hasNext` again to continue as if nothing happened. `hasNext` is now tail recursive, so the stack won't blow up.

Other solutions I could think of:

- Transform the iterator to return `Option[ReferenceWithCommit]` (which is a PITA for the user of this iterator).
- Make the client responsible for catching the error (which is an even bigger PITA)
- Retry N times (which is @smola's quick fix that's posted on the issue), but if this fails all the N times, an exception is thrown, which leaves us with the same problem, just a different type of exception.

### CODE REVIEW

File: src/main/scala/tech/sourced/engine/iterator/CommitIterator.scala [hunk 1]
```diff
@@ -153,14 +156,34 @@ class RefWithCommitIterator(repo: Repository,
...
+    * Returns the next [[ReferenceWithCommit]]. It should never be called after
+    * hasNext has returned "false", since this can lead to incorrect results.
+    *
+    * @return a reference with commit
+    */
   override def next(): ReferenceWithCommit = {
-    val result: ReferenceWithCommit = ReferenceWithCommit(actualRef, commits.next(), index)
-    index += 1
-    result
+    nextResult
```
Comment (smola) [inline src/main/scala/tech/sourced/engine/iterator/CommitIterator.scala]: But this means that if you call `next()` without calling `hasNext()`, you get the same result, right?

Comment (erizocosmico) [reply src/main/scala/tech/sourced/engine/iterator/CommitIterator.scala]: Yep. But that's kind of a given, if you're iterating you need to ask it if it has anything before asking for that anything

**Comment by erizocosmico** [comment]
Updated the PR, there was a bug in it. Now repeated calls to `hasNext` return `true` until the next result has been consumed.

File: src/main/scala/tech/sourced/engine/iterator/CommitIterator.scala [hunk 2]
```diff
@@ -147,19 +160,40 @@ class RefWithCommitIterator(repo: Repository,
...
+      // continue with the next. If we don't preload, the exception will
+      // happen in next, and that's an odd behaviour. This behaviour should
+      // be completely transparent to the iterator user.
+      try {
+        nextResult = ReferenceWithCommit(actualRef, commits.next(), index)
+        index += 1
+        true
+      } catch {
+        case e: RevWalkException =>
+          log.warn("rev walk error", e)
```
Comment (bzz) [inline src/main/scala/tech/sourced/engine/iterator/CommitIterator.scala]: Quick question - do you think it could be useful to also include here some information, that would help to identify the repository/.siva file that caused the exception?  I.e from `repo.getConfig()`

File: src/main/scala/tech/sourced/engine/iterator/CommitIterator.scala (hunk 1 above)
Comment (smola) [reply src/main/scala/tech/sourced/engine/iterator/CommitIterator.scala]: Calling `hasNext` before `next` is definitely the sane thing to do.
Although strictly speaking, `next` is supposed to move to the next item even if `hasNext` hasn't been called. Also, `hasNext + next` should yield the same result as `hasNext + hasNext + next`.

```scala
val it = List("1", "2", "3", "4").iterator
it.next // 1
it.next // 2
it.next // 3
```

Comment (erizocosmico) [reply src/main/scala/tech/sourced/engine/iterator/CommitIterator.scala]: Yes, `hasNext + hasNext + next` yields the same result now.
Though, for obvious reasons with this solution we cannot make the `next + next + next` work. Even before it was not possible, I think, because we were advancing the refs and commits iterators inside `hasNext` too.
