### PR TITLE
Shows supported languages when an unknown one is requested

### LINKED ISSUE #294: Parsing files logs when using unknown lang
discovered at https://github.com/src-d/empathy-sessions/issues/37#issuecomment-470042245

If you choose a nonexistent driver, it outputs the help message, but it should list the available languages instead.

```shell
$ srcd parse uast examples/example.php --lang unknown
Error: language unknown is not supported
Usage:
  srcd parse uast [file-path] [flags]
...
```

### PR DESCRIPTION
**Pull request by se7entyse7en**
Closes #294.

### CODE REVIEW

**Comment by se7entyse7en** [comment]
A couple of things. Do we want to only show the supported languages or do we also want to avoid showing the usage message?

I noticed that there's a `SilenceUsage` flag that avoids printing the usage message. We could also eventually set the usage depending on the error that we encounter, but honestly, I don't like this approach as it seems a bit hacky.

Another thing that I noticed is that the error is actually printed twice, are we ok with that?

Screenshot 2019-03-12 at 23 20 44

We could eventually hide the first one using the `SilenceErrors` flag.

Here how the error appears depending on these two above-mentioned flags:

1. `SilenceUsage: true` and `SilenceErrors: false`

    Screenshot 2019-03-12 at 23 23 25

2. `SilenceUsage: false` and `SilenceErrors: true`

    Screenshot 2019-03-12 at 23 24 09

3. `SilenceUsage: true` and `SilenceErrors: true`

    Screenshot 2019-03-12 at 23 24 48

**Comment by se7entyse7en** [comment]
I've just noticed that this is kind of related to https://github.com/src-d/engine/issues/291.

File: cmd/srcd/cmd/parse.go [hunk 1]
```diff
@@ -95,8 +96,11 @@ The remaining nodes are printed to standard output in JSON format.`,
 			return fmt.Errorf("could not list drivers: %v", err)
 		}
 
-		if !isSupportedLanguage(resp.Drivers, lang) {
-			return fmt.Errorf("language %s is not supported", lang)
+		langaugesSuppInfo := getLanguagesSupportInfo(resp.Drivers, lang)
```
Comment (carlosms) [inline cmd/srcd/cmd/parse.go]:
```suggestion
		languagesSuppInfo := getLanguagesSupportInfo(resp.Drivers, lang)
```

File: cmd/srcd/cmd/parse.go [hunk 2]
```diff
@@ -216,12 +220,25 @@ func parseLang(ctx context.Context, client api.EngineClient, path string, b []by
...
 }
 
-func isSupportedLanguage(supportedDrivers []*api.ListDriversResponse_DriverInfo, desired string) bool {
+type languageSupportInfo struct {
+	supported   []string
+	requested   string
+	isSupported bool
+}
+
+func getLanguagesSupportInfo(supportedDrivers []*api.ListDriversResponse_DriverInfo, desired string) *languageSupportInfo {
```
Comment (carlosms) [inline cmd/srcd/cmd/parse.go]: For some reason this feels odd. The struct return type is there to provide the info you need to build the error message, only in case of error.
Instead of that, we could build the nice error message inside this function. Something like:
```go
func checkSupportedLanguage(supportedDrivers []*api.ListDriversResponse_DriverInfo, desired string) error
```

**Comment by smacker** [comment]
Let's keep duplicated error for this PR. It's how all other errors work right now.
And fix it in another PR. (from the screenshots above I prefer `SilenceUsage: false and SilenceErrors: true` but maybe it's not the best output in some other cases)

File: cmd/srcd/cmd/parse.go (hunk 2 above)
Comment (se7entyse7en) [reply cmd/srcd/cmd/parse.go]: done, I already squashed it as it is a very small thing.

**Comment by se7entyse7en** [comment]
Later I'm gonna create the issue for [this](https://github.com/src-d/engine/pull/319#issuecomment-472383336).
