### PR TITLE
Avoid error when running sourced with broken workdir

### LINKED ISSUE #12: Handle empty `.srcd` when other commands are executed before `install`
Handle empty `.srcd` when other commands are executed before `install`:
```
$ rm -rf ~/.srcd
$ sandbox-ce stop
chdir /home/cmartin/.srcd/workdirs/__active__: no such file or directory
```

### PR DESCRIPTION
**Pull request by dpordomingo**
fix #12 

Problem to be solved:
- Let the users know that they must run `init` before other commands when there's no `~/.srcd`

to run 'init' on beforehand.

## Description of the problem.

The issue can appear in different situations, and the way to solve it depends on the sandbox state.

- sandbox is not running 
    - (missing `_active_`) &rar; `status|start|stop` &rar; ERROR(`_active_` not found)
    - (corrupted `_active_`) &rarr; `status|start|stop` &rarr; NOOP. `sourced` doesn't know the containers
    - **solution**: in both cases, the users needs to know tha they should run `init` again
- `init A` &rarr; (missing/corrupted `_active_`) &rarr; `init B` &rarr; ERROR(port conflicts), because intermediate `stop` failed, because `sourced` doesn't know how to stop old containers.
    - **solution**: to run `init A` again (to restore `_active_`), and then `init B`; but if `A` no longer exists, it is needed to manually stop the containers.

## proposed change (what this PR offers)
**to check the state of the `workdir`, and notice the user if needed**

- sandbox is not running &rarr; (missing/corrupted `_active_`) &rarr; `status|start|stop` &rarr; HINT(run 'init')
- `init A` &rarr; (missing/corrupted `_active_`) &rarr; `init B` &rarr; _same as currently_: ERROR(port conflict)

### improval over the current proposal (_tbd_ in this or other PR if you like it):
- `init A`
    - (corrupted `_active_`) &rarr; `init B` &rarr; since intermediate `stop` will fail, break the execution in order to prevent initializing `B` (that would fail because of the port conflict), and suggest to run again `init A` before retrying `init B`
    - (missing `_active_`) &rarr; _same as currently_: ERROR(port conflict), that can be only solved with manual `init A`, that can not be guessed by `sourced`

## alternative:
- to suggest `init` whenever `sourced` command fails
    - would not work because there are problems that are not recoverable by doing an `init`
- to suggest running `init` if `~/.srcd` is deleted
    - it won't cover when there are already running containers, and `init` because of a port conflict, 
    - it won't cover the case of a corrupted `_active_`, and commands like `status` or `workdir` will lie to the user reporting nothing installed even when there could be a running sandbox.

### CODE REVIEW

File: cmd/sourced/cmd/root.go [hunk 1]
```diff
@@ -35,5 +46,11 @@ type Command struct {
 // Execute adds all child commands to the root command and sets flags appropriately.
 // This is called by main.main(). It only needs to happen once to the rootCmd.
 func Execute() {
-	rootCmd.RunMain()
+	if err := rootCmd.Run(os.Args); err != nil {
+		if errors.Cause(err).Error() == workdir.ErrWrongWorkdir.Error() {
```
Comment (dpordomingo) [inline cmd/sourced/cmd/root.go]: This would be much cleaner if we'd use `src-d/go-errors`, e.g 
```suggestion
		if ErrWrongWorkdir.Is(err) {
```
https://github.com/src-d/go-errors/blob/master/example_test.go#L54

**Review by dpordomingo — COMMENTED** [review]
Is there any strong reason for not using `src-d/go-errors`?

File: cmd/sourced/cmd/root.go (hunk 1 above)
Comment (carlosms) [reply cmd/sourced/cmd/root.go]: I'm ok using `go-errors`

**Review by carlosms — APPROVED** [review]
LGTM.
But I wonder if it would be easier to just return an error from `ValidateWorkdir` that already says `Cannot perform this action...`

**Comment by smacker** [comment]
Good. But let's simplify errors.

**Comment by dpordomingo** [comment]
sure @smacker 
Is your comment aligned with @carlosms [message](https://github.com/src-d/sourced-ce/pull/31#pullrequestreview-247054868)?

Could you help me with that?

Current implementation of `ValidateWorkdir` can return 4 different errors:
- _"could not find workdir"_
- _"passed workdir is not a dir"_
- _"passed workdir lacks of `docker-compose.yml`"_
- _"passed workdir lacks of `.env`"_

Would you merge all of them to be _"Cannot perform this action"_
I'd prefer _"Passed workdir is not valid"_

But I'd really prefer to explain why (at least differentiating between missing `docker-compose.yml`, missing `.env` and no workdir at all) 

wdyt?

**Comment by smacker** [comment]
Aligned. But I see your point too. How about something like this?

workdir.go:
```go
var ValidationError = errors.NewKind("workdir %s is not valid: %s")

func ValidateWorkdir(dir string) error {
   ...
   return ValidationError.New(dir, "is not a dir")
   return ValidationError.New(dir, "docker-compose.yml not found")
   ...
}
```

root.go:
```go
func main() {
    if workdir.ValidationError.Is(err) {
      ...
    }
}
```

That is simpler that current code and does what you prefer.

**Comment by dpordomingo** [comment]
Thanks for your suggestions @smacker 
Done by 53f3adb

In a further iteration, we can just "migrate" to `go-errors` for the whole project. If you agree, let me know and I'll open that issue.

File: cmd/sourced/cmd/root.go [hunk 2]
```diff
@@ -35,5 +41,14 @@ type Command struct {
 // Execute adds all child commands to the root command and sets flags appropriately.
 // This is called by main.main(). It only needs to happen once to the rootCmd.
 func Execute() {
-	rootCmd.RunMain()
+	if err := rootCmd.Run(os.Args); err != nil {
+		if workdir.ErrWrongWorkdir.Is(err) {
```
Comment (smacker) [inline cmd/sourced/cmd/root.go]: nit pic: `workdir.ErrWrongWorkdir` -> `workdir` repeated 2 times in the name of package an in the name of error.

File: cmd/sourced/compose/compose.go [hunk 3]
```diff
@@ -40,6 +40,10 @@ func (c *Compose) RunWithIO(ctx context.Context, stdin io.Reader,
 		return err
 	}
 
+	if err := workdir.ValidateWorkdir(dir); err != nil {
```
Comment (smacker) [inline cmd/sourced/compose/compose.go]: nit pic: `workdir.ValidateWorkdir` -> `workdir` repeated 2 times in the name of package an in the name of function.

**Comment by dpordomingo** [comment]
Thanks for being nit picker @smacker.
- ~`workdir.ErrWrongWorkdir`~ &rarr; `workdir.ErrMalformed`
- ~`workdir.ValidateWorkdir(dir string)`~ &rarr: `workdir.Validate(dir string)`

feel free to propose any other alternative :)

**Review by smacker — APPROVED** [review]
